### ISSUE TITLE
Matching bug

### ISSUE THREAD

**Issue by Paikan** [JDonner/NoAho#2]
```python
from noaho import NoAho

a = NoAho()
a.add('cisco', 'cisco')
a.add('em', 'em')
a.add('cisco systems australia', 'cisco systems')
for match in a.findall_long('cisco systems'):
    print(match)

# match only with:
# (10, 12, 'em')
#
# expected match would be:
# (0, 5, 'cisco'), (10, 12, 'em')
```

**Comment by JDonner** [comment]
Hey, I've fixed it (will upload it within a couple of hours). Do you mind if I use your testcase verbatim as a test? I always feel more comfortable if I can use the exact test case.

**Comment by Paikan** [comment]
Fantastic thanks!

Sure use it!

On Tuesday, February 17, 2015, Jeff Donner <notifications@github.com> wrote:

> Hey, I've fixed it (will upload it within a couple of hours). Do you mind
> if I use your testcase verbatim as a test? I always feel more comfortable
> if I can use the exact test case.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/JDonner/NoAho/issues/2#issuecomment-74615779>.
>


-- 
Benjamin DEVEZE
